services:
  horasapi:
    container_name: horasapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5004:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=person.db
      - POSTGRES_DB=${POSTGRES_DB}

  person.db:
    image: postgres:latest
    container_name: person.db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/new-data
    volumes:
      - ./new-data:/var/lib/postgresql/new-data
    ports:
      - "5432:5432"

